class AnilistConstant {
  static const List<String> mediaGenres = [
    "Action",
    "Adventure",
    "Comedy",
    "Drama",
    "Ecchi",
    "Fantasy",
    "Hentai",
    "Horror",
    "Mahou Shoujo",
    "Mecha",
    "Music",
    "Mystery",
    "Psychological",
    "Romance",
    "Sci-Fi",
    "Slice of Life",
    "Sports",
    "Supernatural",
    "Thriller"
  ];

  static const mediaTags = [
    "4-koma",
    "Achromatic",
    "Achronological Order",
    "Acting",
    "Adoption",
    "Advertisement",
    "Afterlife",
    "Age Gap",
    "Age Regression",
    "Agender",
    "Agriculture",
    "Ahegao",
    "Airsoft",
    "Alchemy",
    "Aliens",
    "Alternate Universe",
    "American Football",
    "Amnesia",
    "Amputation",
    "Anachronism",
    "Anal Sex",
    "Angels",
    "Animals",
    "Anthology",
    "Anthropomorphism",
    "Anti-Hero",
    "Archery",
    "Armpits",
    "Artificial Intelligence",
    "Asexual",
    "Ashikoki",
    "Asphyxiation",
    "Assassins",
    "Astronomy",
    "Athletics",
    "Augmented Reality",
    "Autobiographical",
    "Aviation",
    "Badminton",
    "Band",
    "Bar",
    "Baseball",
    "Basketball",
    "Battle Royale",
    "Biographical",
    "Bisexual",
    "Blackmail",
    "Body Horror",
    "Body Swapping",
    "Bondage",
    "Boobjob",
    "Boxing",
    "Boys' Love",
    "Bullying",
    "Butler",
    "Calligraphy",
    "Cannibalism",
    "Card Battle",
    "Cars",
    "Centaur",
    "CGI",
    "Cheerleading",
    "Chibi",
    "Chimera",
    "Chuunibyou",
    "Circus",
    "Classic Literature",
    "Clone",
    "College",
    "Coming of Age",
    "Conspiracy",
    "Cosmic Horror",
    "Cosplay",
    "Crime",
    "Crossdressing",
    "Crossover",
    "Cult",
    "Cultivation",
    "Cumflation",
    "Cunnilingus",
    "Cute Boys Doing Cute Things",
    "Cute Girls Doing Cute Things",
    "Cyberpunk",
    "Cyborg",
    "Cycling",
    "Dancing",
    "Death Game",
    "Deepthroat",
    "Defloration",
    "Delinquents",
    "Demons",
    "Denpa",
    "Desert",
    "Detective",
    "DILF",
    "Dinosaurs",
    "Disability",
    "Dissociative Identities",
    "Dragons",
    "Drawing",
    "Drugs",
    "Dullahan",
    "Dungeon",
    "Dystopian",
    "E-Sports",
    "Economics",
    "Educational",
    "Elf",
    "Ensemble Cast",
    "Environmental",
    "Episodic",
    "Ero Guro",
    "Espionage",
    "Exhibitionism",
    "Facial",
    "Fairy",
    "Fairy Tale",
    "Family Life",
    "Fashion",
    "Feet",
    "Fellatio",
    "Female Harem",
    "Female Protagonist",
    "Femboy",
    "Femdom",
    "Fencing",
    "Firefighters",
    "Fishing",
    "Fitness",
    "Flash",
    "Flat Chest",
    "Food",
    "Football",
    "Foreign",
    "Found Family",
    "Fugitive",
    "Full CGI",
    "Full Color",
    "Futanari",
    "Gambling",
    "Gangs",
    "Gender Bending",
    "Ghost",
    "Go",
    "Goblin",
    "Gods",
    "Golf",
    "Gore",
    "Group Sex",
    "Guns",
    "Gyaru",
    "Handball",
    "Handjob",
    "Henshin",
    "Heterosexual",
    "Hikikomori",
    "Historical",
    "Homeless",
    "Human Pet",
    "Hypersexuality",
    "Ice Skating",
    "Idol",
    "Incest",
    "Inseki",
    "Irrumatio",
    "Isekai",
    "Iyashikei",
    "Josei",
    "Judo",
    "Kaiju",
    "Karuta",
    "Kemonomimi",
    "Kids",
    "Kuudere",
    "Lacrosse",
    "Lactation",
    "Language Barrier",
    "Large Breasts",
    "LGBTQ+ Themes",
    "Lost Civilization",
    "Love Triangle",
    "Mafia",
    "Magic",
    "Mahjong",
    "Maids",
    "Makeup",
    "Male Harem",
    "Male Protagonist",
    "Marriage",
    "Martial Arts",
    "Masochism",
    "Masturbation",
    "Medicine",
    "Memory Manipulation",
    "Mermaid",
    "Meta",
    "MILF",
    "Military",
    "Mixed Gender Harem",
    "Monster Boy",
    "Monster Girl",
    "Mopeds",
    "Motorcycles",
    "Musical",
    "Mythology",
    "Nakadashi",
    "Necromancy",
    "Nekomimi",
    "Netorare",
    "Netorase",
    "Netori",
    "Ninja",
    "No Dialogue",
    "Noir",
    "Non-fiction",
    "Nudity",
    "Nun",
    "Office Lady",
    "Oiran",
    "Ojou-sama",
    "Omegaverse",
    "Orphan",
    "Otaku Culture",
    "Outdoor",
    "Pandemic",
    "Parkour",
    "Parody",
    "Philosophy",
    "Photography",
    "Pirates",
    "Poker",
    "Police",
    "Politics",
    "Post-Apocalyptic",
    "POV",
    "Pregnant",
    "Primarily Adult Cast",
    "Primarily Child Cast",
    "Primarily Female Cast",
    "Primarily Male Cast",
    "Primarily Teen Cast",
    "Prison",
    "Prostitution",
    "Public Sex",
    "Puppetry",
    "Rakugo",
    "Rape",
    "Real Robot",
    "Rehabilitation",
    "Reincarnation",
    "Religion",
    "Revenge",
    "Rimjob",
    "Robots",
    "Rotoscoping",
    "Rugby",
    "Rural",
    "Sadism",
    "Samurai",
    "Satire",
    "Scat",
    "School",
    "School Club",
    "Scissoring",
    "Scuba Diving",
    "Seinen",
    "Sex Toys",
    "Shapeshifting",
    "Ships",
    "Shogi",
    "Shoujo",
    "Shounen",
    "Shrine Maiden",
    "Skateboarding",
    "Skeleton",
    "Slapstick",
    "Slavery",
    "Software Development",
    "Space",
    "Space Opera",
    "Spearplay",
    "Squirting",
    "Steampunk",
    "Stop Motion",
    "Succubus",
    "Suicide",
    "Sumata",
    "Sumo",
    "Super Power",
    "Super Robot",
    "Superhero",
    "Surfing",
    "Surreal Comedy",
    "Survival",
    "Sweat",
    "Swimming",
    "Swordplay",
    "Table Tennis",
    "Tanks",
    "Tanned Skin",
    "Teacher",
    "Teens' Love",
    "Tennis",
    "Tentacles",
    "Terrorism",
    "Threesome",
    "Time Manipulation",
    "Time Skip",
    "Tokusatsu",
    "Tomboy",
    "Torture",
    "Tragedy",
    "Trains",
    "Transgender",
    "Travel",
    "Triads",
    "Tsundere",
    "Twins",
    "Urban",
    "Urban Fantasy",
    "Vampire",
    "Video Games",
    "Vikings",
    "Villainess",
    "Virginity",
    "Virtual World",
    "Volleyball",
    "Vore",
    "Voyeur",
    "VTuber",
    "War",
    "Watersports",
    "Werewolf",
    "Witch",
    "Work",
    "Wrestling",
    "Writing",
    "Wuxia",
    "Yakuza",
    "Yandere",
    "Youkai",
    "Yuri",
    "Zombie",
    "Zoophilia"
  ];
}
